version: 2

jobs:
  build:
    docker:
      - image: msvrtan/square:0.2.2
    working_directory: /var/www
    parallel: 1
    steps:
      - checkout

      - run:
          name: Composer install
          command: composer install --prefer-dist --no-interaction

      - run:
          name: Check code standards
          command: ./vendor/bin/php-cs-fixer fix --dry-run --diff

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
